version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  build:
    commands:
      - echo "Building, Testing and Packaging the application..."
      - mvn package

  post_build:
    commands:
      - echo "Build, Testing and Packaging completed."

artifacts:
  files:
    - target/*.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
